language: php
dist: trusty
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5

install:
  - composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

script:
  - vendor/bin/phpunit --verbose
