language: php

matrix:
  fast_finish: true
  include:
    - php: nightly
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5

  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

script:
  - vendor/bin/phpunit --verbose
